### ISSUE TITLE
Don't start a parallel pool if not needed

### ISSUE THREAD

**Issue by aledinola** [vfitoolkit/VFIToolkit-matlab#4]
I noticed that to compute the distribution using the Tan method (which is the default) we do not use parallel computing on CPU, which makes sense. But nonetheless the code automatically starts a parallel pool, which slows things down without any apparent benefit. The problem is in these lines of code:

```
if ~isfield(simoptions,'ncores')
        try
            PoolDetails=gcp;
            simoptions.ncores=PoolDetails.NumWorkers;
        catch
            simoptions.ncores=1;
        end
    end
```

which are around line 55 in **StationaryDist_FHorz_Case1**. I think that there is no need to start a parallel pool on the cpu: with the Tan improvement we do sparse matrices on the cpu, and when using gpuArray we don't need a parallel pool either.

**Comment by robertdkirkby** [comment]
Fixed. Thanks.

I had also noticed it was spinning up the parallel pool, but because this only happened first time it was called (so doesn't matter for general eqm, etc.) and because I didn't know what was causing it I just left it.
