### ISSUE TITLE
Small change to StationaryDist_FHorz_Case1_Iteration_TwoProbs_raw

### ISSUE THREAD

**Issue by aledinola** [vfitoolkit/VFIToolkit-matlab#6]
In StationaryDist_FHorz_Case1_Iteration_TwoProbs_raw, I would replace the line 27 of the function 

`Gammatranspose=sparse(Policy_aprimez(:,:,jj),II2,PolicyProbs(:,:,jj),N_a*N_z,N_a*N_z); `

with 

```
Gammatranspose=sparse(Policy_aprimez(:,1,jj),II1,PolicyProbs(:,1,jj),N_a*N_z,N_a*N_z)+...
        sparse(Policy_aprimez(:,2,jj),II1,PolicyProbs(:,2,jj),N_a*N_z,N_a*N_z);
```

On line 21, precompute
`II1=(1:1:N_a*N_z)';`

instead of 

`II2=[1:1:N_a*N_z; 1:1:N_a*N_z]';`

**Comment by robertdkirkby** [comment]
Ran some runtime comparisons, found that the existing approach is faster on average, although the differences are negligible.
http://discourse.vfitoolkit.com/t/example-attanasio-low-sanchez-marcos-2008/257/21?u=robertdkirkby
