### ISSUE TITLE
Automatic expansion in infinite horizon vfi

### ISSUE THREAD

**Issue by aledinola** [vfitoolkit/VFIToolkit-matlab#7]
In line 31 of ValueFnIter/InfHorz/ValueFnIter_Case1_NoD_Par2_raw.m, one can use automatic expansion (better for memory and speed)

The term EVz is of size (na,1) and is automatically expanded to (na,na), so I would eliminate the multiplication by ones(1,na)

**Comment by robertdkirkby** [comment]
Done. Thanks for pointing it out. Actually these infinite horizon codes are so dated it is a bit embarrassing, so I switched the expectations to parallelize over z properly while I was there (and did the 'with decision variable' version too). Makes everything a little bit faster still :)

Pushed:
https://github.com/vfitoolkit/VFIToolkit-matlab/commit/7bec6111c76d28c9dc271adf9ae6185f452f4398
