### ISSUE TITLE
Interpolation: max vs discretize

### ISSUE THREAD

**Issue by aledinola** [vfitoolkit/VFIToolkit-matlab#8]
If max() is faster then discretize for **small** grids, then the following seems wrong. Should switch the two cases

% For small aprimeVals and a_grid, max() is faster than discretize()
    % http://discourse.vfitoolkit.com/t/example-attanasio-low-sanchez-marcos-2008/257/25
    if N_d*N_a2*N_a2>1000000
[~,a2primeIndexes]=max((a2_grid>a2primeVals),[],1); % Keep the dimension corresponding to aprimeVals, minimize over the a_grid dimension
        %

**Comment by robertdkirkby** [comment]
I understand what you are saying but I'm lost in terms of where in the codes you are talking about? Where in the codes do you mean to change the if-statement?

**Comment by aledinola** [comment]
See line 119 of 
aprimeFnMatrix/CreateExperienceAssetFnMatrix_Case1.m
Maybe also other functions in the same subfolder

**Comment by aledinola** [comment]
Also line 359 of CreateExperienceAssetuFnMatrix_Case1.m

**Comment by robertdkirkby** [comment]
Fixed: https://github.com/vfitoolkit/VFIToolkit-matlab/commit/9031a99bbc122a00036be07b9944c80911e3f552

I'm glad you spotted that, not sure I ever would have!
